language: go
go:
- 1.12.x
env:
- DEP_VERSION="0.5.1"
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- "( cd grammar && ./generate-parser )"
- "openssl aes-256-cbc -K $encrypted_dfa6417bf089_key -iv $encrypted_dfa6417bf089_iv -in upload-user.key.enc -out upload-user.key -d"
install:
- dep ensure
deploy:
  provider: gcs
  key_file: upload-user.key
  bucket: published-releases
  upload_dir: conseq
  edge: true
